export const leaderboard: Leaderboard[] = [
    {
        id: 1,
        username: "Linaceous",
        rank: "shark",
        stars: 3,
        pearls: 32000,
    },
    {
        id: 2,
        username: "Fishwife",
        rank: "shark",
        stars: 2,
        pearls: 24200,
    },
    {
        id: 3,
        username: "Howbeit",
        rank: "shark",
        stars: 1,
        pearls: 16000,
    },
    {
        id: 4,
        username: "HerrmannWhorl",
        rank: "dolphin",
        stars: 2,
        pearls: 14000,
    },
    {
        id: 5,
        username: "Nautics",
        rank: "dolphin",
        stars: 1,
        pearls: 12200,
    },
    {
        id: 6,
        username: "Pratfall",
        rank: "fish",
        stars: 3,
        pearls: 10500,
    },
    {
        id: 7,
        username: "KrislovWye",
        rank: "fish",
        stars: 2,
        pearls: 8000,
    },
    {
        id: 8,
        username: "ZehkraBippy",
        rank: "fish",
        stars: 1,
        pearls: 6000,
    },
    {
        id: 9,
        username: "Hederaceous",
        rank: "crab",
        stars: 3,
        pearls: 4200,
    },
    {
        id: 10,
        username: "Tomfoolery",
        rank: "crab",
        stars: 2,
        pearls: 2000,
    },
    {
        id: 11,
        username: "Crescendo",
        rank: "crab",
        stars: 1,
        pearls: 1000,
    },
    {
        id: 12,
        username: "Mari0_Petrel",
        rank: "crab",
        stars: 1,
        pearls: 1000,
    },
];
